FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY protection_system /protection_system

#RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /protection_system
#USER appuser

WORKDIR /protection_system
CMD ["python", "system.py"]

EXPOSE 5068